name: Metrics

on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch:

permissions:
  contents: write   # 👈 give the bot permission to commit
  issues: read
  pull-requests: read

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Eskinder185
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York
