name: Metrics
on:
  schedule:
    - cron: "0 * * * *" # every hour
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Eskinder185
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York
